theme = "rose_pine_dawn"

[editor]
bufferline = "multiple"
cursorline = true
line-number = "relative"
rulers = [120]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
A-h = ":run-shell-command . ~/scripts/zellij-floating-fzf.sh"

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
